package online.qsx.mapper;

import java.util.List;
import online.qsx.model.Area;
import online.qsx.model.AreaCriteria;
import online.qsx.model.City;
import org.apache.ibatis.annotations.Param;

public interface AreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_area
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int countByExample(AreaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_area
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int deleteByExample(AreaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_area
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_area
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_area
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int insertSelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_area
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    List<Area> selectByExample(AreaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_area
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    Area selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_area
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Area record, @Param("example") AreaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_area
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int updateByExample(@Param("record") Area record, @Param("example") AreaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_area
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int updateByPrimaryKeySelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_area
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int updateByPrimaryKey(Area record);

    List<Area> queryAreaByCityId(Integer father);
}