package online.qsx.mapper;

import java.util.List;
import online.qsx.model.City;
import online.qsx.model.CityCriteria;
import org.apache.ibatis.annotations.Param;

public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_city
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int countByExample(CityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_city
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int deleteByExample(CityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_city
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_city
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_city
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int insertSelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_city
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    List<City> selectByExample(CityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_city
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    City selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_city
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") City record, @Param("example") CityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_city
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int updateByExample(@Param("record") City record, @Param("example") CityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_city
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int updateByPrimaryKeySelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_city
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int updateByPrimaryKey(City record);

    List<City> queryCityByProvinceId(Integer provinceid);
}