package online.qsx.mapper;

import java.util.List;
import online.qsx.model.Province;
import online.qsx.model.ProvinceCriteria;
import org.apache.ibatis.annotations.Param;

public interface ProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int countByExample(ProvinceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int deleteByExample(ProvinceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int insert(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int insertSelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    List<Province> selectByExample(ProvinceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    Province selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Province record, @Param("example") ProvinceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int updateByExample(@Param("record") Province record, @Param("example") ProvinceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int updateByPrimaryKeySelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    int updateByPrimaryKey(Province record);
}