package online.qsx.model;

import java.io.Serializable;

public class City implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_city.id
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_city.cityID
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    private Long cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_city.city
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_city.father
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    private Long father;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bs_city
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_city.id
     *
     * @return the value of bs_city.id
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_city.id
     *
     * @param id the value for bs_city.id
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_city.cityID
     *
     * @return the value of bs_city.cityID
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    public Long getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_city.cityID
     *
     * @param cityid the value for bs_city.cityID
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    public void setCityid(Long cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_city.city
     *
     * @return the value of bs_city.city
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_city.city
     *
     * @param city the value for bs_city.city
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_city.father
     *
     * @return the value of bs_city.father
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    public Long getFather() {
        return father;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_city.father
     *
     * @param father the value for bs_city.father
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    public void setFather(Long father) {
        this.father = father;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_city
     *
     * @mbggenerated Thu Apr 19 22:13:52 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cityid=").append(cityid);
        sb.append(", city=").append(city);
        sb.append(", father=").append(father);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}